# Generated by Django 2.1.7 on 2019-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20190227_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-c_time'], 'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='remark',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
