# Generated by Django 2.1.7 on 2019-02-28 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_auto_20190227_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='商户名称')),
                ('phone', models.CharField(max_length=128, verbose_name='商户电话')),
                ('email', models.CharField(blank=True, default='', max_length=256, verbose_name='邮件地址')),
                ('info', models.TextField(blank=True, default='', max_length=256, verbose_name='店铺信息')),
                ('type', models.CharField(choices=[('sell', '销售'), ('fixing', '维修'), ('recycle', '回收')], default='', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand'),
        ),
    ]
