# Generated by Django 2.1.7 on 2019-02-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_auto_20190228_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('it', '信息部'), ('hr', '人力部'), ('administrative', '行政部'), ('financial', '财务部'), ('manager', '总经办'), ('sales', '销售部'), ('market', '市场部')], default='', max_length=32, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.Category', verbose_name='设备类别'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='img',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(max_length=128, unique=True, verbose_name='SN码/序列号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('unused', '库存'), ('useing', '使用中'), ('fixing', '维修中'), ('scrap', '报废')], default='库存', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.User', verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
    ]
