# Generated by Django 2.1.7 on 2019-02-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_auto_20190228_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='procurement',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Merchant', verbose_name='采购方'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
    ]
