# Generated by Django 2.1.7 on 2019-03-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0019_auto_20190303_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='maintain',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixer', to='ems.Merchant', verbose_name='维修方'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price_in',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price_out',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
    ]
