# Generated by Django 2.1.7 on 2019-03-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0020_auto_20190305_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_in',
            field=models.CharField(blank=True, max_length=128, verbose_name='买入价格'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_out',
            field=models.CharField(blank=True, max_length=128, verbose_name='卖出价格'),
        ),
    ]
