# Generated by Django 2.1.7 on 2019-03-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0021_auto_20190305_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maintain',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixer', to='ems.Merchant', verbose_name='维修方'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_in',
            field=models.CharField(max_length=128, verbose_name='买入价格'),
        ),
    ]
