# Generated by Django 2.1.7 on 2019-03-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0023_auto_20190305_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='设备名称')),
                ('sn', models.CharField(db_index=True, max_length=128, verbose_name='SN码/序列号')),
                ('img', models.CharField(blank=True, default='', max_length=256, verbose_name='图片地址')),
                ('state', models.CharField(choices=[('unused', '库存'), ('useing', '使用中'), ('fixing', '维修中'), ('scrap', '报废'), ('problem', '问题')], default='库存', max_length=32, verbose_name='状态')),
                ('remark', models.TextField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('price_in', models.CharField(max_length=128, verbose_name='买入价格')),
                ('price_out', models.CharField(blank=True, max_length=128, verbose_name='卖出价格')),
                ('c_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Category', verbose_name='设备类别')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maintain', models.ForeignKey(blank=True, db_constraint=False, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Merchant', verbose_name='维修方')),
                ('procurement', models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Merchant', verbose_name='采购方')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.User', verbose_name='使用人')),
            ],
            options={
                'verbose_name': 'historical 设备',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-c_time'], 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.User', verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='标题'),
        ),
    ]
