# Generated by Django 2.1.7 on 2019-03-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0026_auto_20190305_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('unused', '库存'), ('useing', '使用中'), ('fixing', '维修中'), ('scrap', '报废'), ('problem', '问题'), ('sell', '卖出')], default='库存', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='state',
            field=models.CharField(choices=[('unused', '库存'), ('useing', '使用中'), ('fixing', '维修中'), ('scrap', '报废'), ('problem', '问题'), ('sell', '卖出')], default='库存', max_length=32, verbose_name='状态'),
        ),
    ]
