# Generated by Django 2.1.7 on 2019-03-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0039_auto_20190320_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.CharField(max_length=128, verbose_name='内容')),
                ('is_fix', models.BooleanField(default=False, verbose_name='是否解决')),
                ('level', models.CharField(choices=[('normal', '一般'), ('warning', '警告'), ('danger', '严重')], default='一般', max_length=32, verbose_name='等级')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '标题',
                'verbose_name_plural': '标题',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='joke',
            name='content',
            field=models.CharField(max_length=128, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='risk',
            name='refer_equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ems.Equipment', verbose_name='相关设备'),
        ),
    ]
