# Generated by Django 2.1.7 on 2019-03-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0040_auto_20190322_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['-c_time'], 'verbose_name': '风险点', 'verbose_name_plural': '风险点'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='refer_equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ems.Equipment', verbose_name='相关设备'),
        ),
    ]
