# Generated by Django 2.1.7 on 2019-03-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0042_auto_20190322_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=256, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('chat_from', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_from', to='ems.User', verbose_name='发送人')),
                ('chat_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_to', to='ems.User', verbose_name='接收人')),
            ],
            options={
                'verbose_name': '聊天',
                'verbose_name_plural': '聊天',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='refer_equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ems.Equipment', verbose_name='相关设备'),
        ),
    ]
