# Generated by Django 2.1.7 on 2019-03-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0043_auto_20190326_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='warranty',
            field=models.CharField(default='365', max_length=128, verbose_name='保修'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='warranty',
            field=models.CharField(default='365', max_length=128, verbose_name='保修'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='refer_equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ems.Equipment', verbose_name='相关设备'),
        ),
    ]
