# Generated by Django 2.1.7 on 2019-03-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0044_auto_20190326_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Could_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', max_length=256, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('advice_price', models.CharField(max_length=128, verbose_name='建议价格')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '建议出售设备',
                'verbose_name_plural': '建议出售设备',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='brand',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ems.Brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='refer_equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ems.Equipment', verbose_name='相关设备'),
        ),
        migrations.AddField(
            model_name='could_sell',
            name='equ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equ', to='ems.Equipment', verbose_name='相关设备'),
        ),
    ]
